services:

  ballancer:
    build: .
    container_name: haproxy_server
    ports:
      - 9001:80
    networks:
      - mynetwork
    depends_on:
      - server1
      - server2

  server1:
    image: nginx:alpine
    container_name: server1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./index1.html:/var/www/html/index.html
    networks:
      - mynetwork

  server2:
    image: nginx:alpine
    container_name: server2
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./index2.html:/var/www/html/index.html
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
